services:

  wa.pizza.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: WA.Pizza/Dockerfile
    depends_on:
      - db
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        
  db:
    container_name: 'pizza-mssql'
    ports:
      - "5433:1433"
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    volumes:
      - mssqldata:/var/opt/mssql    
    
  seq:
    container_name: 'pizza-seq'
    ports:
      - "5300:80"
    environment:
      - ACCEPT_EULA=Y
    restart: unless-stopped